# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 301, 101))
        self.label.setObjectName("label")
        self.look_btn = QtWidgets.QPushButton(Dialog)
        self.look_btn.setGeometry(QtCore.QRect(0, 200, 93, 28))
        self.look_btn.setObjectName("look_btn")
        self.continue_btn = QtWidgets.QPushButton(Dialog)
        self.continue_btn.setGeometry(QtCore.QRect(230, 200, 93, 28))
        self.continue_btn.setObjectName("continue_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Открыть симуляцию"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Вы желаете просмотреть историю</span></p><p><span style=\" font-size:10pt;\"> симуляции или продолжить</span></p><p><span style=\" font-size:10pt;\"> с последнего хода?</span></p></body></html>"))
        self.look_btn.setText(_translate("Dialog", "Просмотреть"))
        self.continue_btn.setText(_translate("Dialog", "Продолжить"))
